export default {
  login: "SAMBIT20",
  id: 50833547,
  node_id: "MDQ6VXNlcjUwODMzNTQ3",
  avatar_url: "https://avatars.githubusercontent.com/u/50833547?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SAMBIT20",
  html_url: "https://github.com/SAMBIT20",
  followers_url: "https://api.github.com/users/SAMBIT20/followers",
  following_url: "https://api.github.com/users/SAMBIT20/following{/other_user}",
  gists_url: "https://api.github.com/users/SAMBIT20/gists{/gist_id}",
  starred_url: "https://api.github.com/users/SAMBIT20/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SAMBIT20/subscriptions",
  organizations_url: "https://api.github.com/users/SAMBIT20/orgs",
  repos_url: "https://api.github.com/users/SAMBIT20/repos",
  events_url: "https://api.github.com/users/SAMBIT20/events{/privacy}",
  received_events_url: "https://api.github.com/users/SAMBIT20/received_events",
  type: "User",
  site_admin: false,
  name: "Sambit Kumar Nanda",
  company: "Zetacx",
  blog: "samnanda.netlify.app",
  location: null,
  email: null,
  hireable: null,
  bio:
    "I love  Programming and, always ready to take new challenges & always curious to learn something new.  ",
  twitter_username: "sambit_dev",
  public_repos: 17,
  public_gists: 5,
  followers: 128,
  following: 17,
  created_at: "2019-05-20T13:05:18Z",
  updated_at: "2021-04-13T10:26:26Z",
};
